name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v1
      with:
        version: latest
    
    - name: Install dependencies
      run: uv sync
    
    - name: Run tests with coverage
      run: uv run pytest --cov=dormatory --cov-report=xml --cov-report=html --cov-report=term-missing -v
    
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/
        retention-days: 30
    
    - name: Display coverage summary
      run: |
        echo "=== Coverage Summary ==="
        uv run coverage report
        echo "========================" 